### ISSUE TITLE
package rename to 'baldr' 

### ISSUE THREAD

**Issue by jackolney** [jackolney/modelr#12]
Norse god of light: https://en.wikipedia.org/wiki/Baldr

**Comment by MilaniC** [comment]
Really useful package. But your do indeed need to change the name as "modelr" is also used for the name of one of the "tidyverse" R packages and this screws this all up in R.

**Comment by richfitz** [comment]
> son of the god Odin

(https://en.wikipedia.org/wiki/Baldr) which is nice from a dependency relationship

**Comment by jackolney** [comment]
This is not a sufficient set of actions, though none others are in the package code and all need doing by @jackolney as admin:

- [x] rename github repo and update url on landing page
- [x] travis/appveyor renaming can be quite difficult to nail down
- [x] The first screenshot in manual.md needs remaking
- [x] rsconnect stuff probably needs work and redeploying

**Comment by jackolney** [comment]
Finally done. Remind me never to rename a package again.
